music = {

    # ── Originals (kept from before) ─────────────────────────────────────────
    "zaalima":                  "https://www.youtube.com/watch?v=hnCsD8jlp2E",
    "o maahi":                  "https://www.youtube.com/watch?v=3YxEAEY8vB4",
    "tu jaane na":              "https://www.youtube.com/watch?v=Jne9t8sHpUc",
    "pehla pyaar":              "https://www.youtube.com/watch?v=0Gxr9nE9YYA",
    "zalim":                    "https://www.youtube.com/watch?v=hhdSyBHuI88",
    "tere sang yaara":          "https://www.youtube.com/watch?v=gIOea2pgfIo",
    "tera fitoor":              "https://www.youtube.com/watch?v=qfdShSZZxlg",
    "hello":                    "https://www.youtube.com/watch?v=gdZLi9oWNZg",

    # ── Arijit Singh ─────────────────────────────────────────────────────────
    "tum hi ho":                "https://www.youtube.com/watch?v=Umqb9KENgmk",
    "ae dil hai mushkil":       "https://www.youtube.com/watch?v=SFAsFoWMCRE",
    "channa mereya":            "https://www.youtube.com/watch?v=fQzVSEOJIH0",
    "kesariya":                 "https://www.youtube.com/watch?v=BddP6PYo2gs",
    "apna bana le":             "https://www.youtube.com/watch?v=m9r6QFQFPRY",
    "raataan lambiyan":         "https://www.youtube.com/watch?v=aO7YpAGyhiU",
    "bekhayali":                "https://www.youtube.com/watch?v=tHWO5A1KHzQ",
    "ilahi":                    "https://www.youtube.com/watch?v=MrChVSJg_nQ",
    "khairiyat":                "https://www.youtube.com/watch?v=O9mECGPQFqE",
    "main hoon hero tera":      "https://www.youtube.com/watch?v=6FURuLKRGMI",
    "agar tum saath ho":        "https://www.youtube.com/watch?v=Jdm2oZaqfZc",
    "hamari adhuri kahani":     "https://www.youtube.com/watch?v=gXAOR2HmbeQ",
    "gerua":                    "https://www.youtube.com/watch?v=BoyEExcKqMQ",
    "phir bhi tumko chahungi":  "https://www.youtube.com/watch?v=q8JKIbMdHos",
    "dil diya gallan":          "https://www.youtube.com/watch?v=xIlcHOfxKKk",
    "soch na sake":             "https://www.youtube.com/watch?v=qJBMzPuGGMY",
    "kuch is tarah":            "https://www.youtube.com/watch?v=TgVrOJwLWNk",
    "meri aashiqui":            "https://www.youtube.com/watch?v=4aXFAfr5qmM",
    "kabira":                   "https://www.youtube.com/watch?v=J_5tAUCCg9c",
    "saware":                   "https://www.youtube.com/watch?v=eGbhFUKr9Kw",
    "kun faya kun":             "https://www.youtube.com/watch?v=T94PHkuydcw",

    # ── Atif Aslam ───────────────────────────────────────────────────────────
    "teri galliyan":            "https://www.youtube.com/watch?v=r8HRDeRqZlI",
    "bairiya":                  "https://www.youtube.com/watch?v=N8E7LGHY2oY",
    "tu jaane na atif":         "https://www.youtube.com/watch?v=Jne9t8sHpUc",
    "doorie":                   "https://www.youtube.com/watch?v=Gp41tiwmDU0",
    "woh lamhe":                "https://www.youtube.com/watch?v=e_kCpEHdHrg",
    "jeena jeena":              "https://www.youtube.com/watch?v=FcPsqh_OSBY",
    "pehli nazar mein":         "https://www.youtube.com/watch?v=1GexkFy4kpU",
    "dil diyan gallan atif":    "https://www.youtube.com/watch?v=xIlcHOfxKKk",
    "tere sang yaara atif":     "https://www.youtube.com/watch?v=gIOea2pgfIo",
    "jab koi baat bigad jaye":  "https://www.youtube.com/watch?v=mJD-3Yh_P2E",
    "aadat":                    "https://www.youtube.com/watch?v=Qq_lxNSHoRM",
    "main rang sharbaton ka":   "https://www.youtube.com/watch?v=TJRCuMpiqXo",
    "tajdar e haram":           "https://www.youtube.com/watch?v=NllGMkbMdZE",
    "ae dil hai mushkil atif":  "https://www.youtube.com/watch?v=SFAsFoWMCRE",
    "o humnava":                "https://www.youtube.com/watch?v=FeAv1LQ6XJA",

    # ── Taylor Swift ─────────────────────────────────────────────────────────
    "anti hero":                "https://www.youtube.com/watch?v=b1kbLwvqugk",
    "shake it off":             "https://www.youtube.com/watch?v=nfWlot6h_JM",
    "blank space":              "https://www.youtube.com/watch?v=e-ORhEE9VVg",
    "love story":               "https://www.youtube.com/watch?v=8xg3vE8Ie_E",
    "bad blood":                "https://www.youtube.com/watch?v=QcIy9NiNbmo",
    "wildest dreams":           "https://www.youtube.com/watch?v=IdneKLhsWOQ",
    "style":                    "https://www.youtube.com/watch?v=sRBsC19UDpM",
    "cruel summer":             "https://www.youtube.com/watch?v=ic8j13piAhQ",
    "cardigan":                 "https://www.youtube.com/watch?v=K-a8s8OLBSE",
    "august":                   "https://www.youtube.com/watch?v=qBmmHFkYCHw",
    "lavender haze":            "https://www.youtube.com/watch?v=FuXNumBwDOM",
    "all too well":             "https://www.youtube.com/watch?v=tollwMNq9B0",
    "22":                       "https://www.youtube.com/watch?v=AgFeZr5ptV8",
    "you belong with me":       "https://www.youtube.com/watch?v=VuNIsY6JdUw",
    "fearless":                 "https://www.youtube.com/watch?v=Y_LbM2AW7Ow",

    # ── BTS ───────────────────────────────────────────────────────────────────
    "dynamite":                 "https://www.youtube.com/watch?v=gdZLi9oWNZg",
    "butter":                   "https://www.youtube.com/watch?v=WMweEpGlu_U",
    "boy with luv":             "https://www.youtube.com/watch?v=XsX3ATc3FbA",
    "dna":                      "https://www.youtube.com/watch?v=MBdVXkSdhwU",
    "fake love":                "https://www.youtube.com/watch?v=7C2z4GqqS5E",
    "idol":                     "https://www.youtube.com/watch?v=pBuZEGYXA6E",
    "life goes on":             "https://www.youtube.com/watch?v=_U1heqZNAyE",
    "permission to dance":      "https://www.youtube.com/watch?v=CuklIb9d3fI",
    "on":                       "https://www.youtube.com/watch?v=mesE1szEfUk",
    "mic drop":                 "https://www.youtube.com/watch?v=kTlv5_nS1sQ",
    "spring day":               "https://www.youtube.com/watch?v=xEeFrLSkMm8",
    "run bts":                  "https://www.youtube.com/watch?v=_4fx3MCE08A",
    "yet to come":              "https://www.youtube.com/watch?v=qGjAWJ2zWWI",

    # ── Justin Bieber ─────────────────────────────────────────────────────────
    "baby":                     "https://www.youtube.com/watch?v=kffacxfA7G4",
    "love yourself":            "https://www.youtube.com/watch?v=oyEuk8j8imI",
    "sorry":                    "https://www.youtube.com/watch?v=fRh_vgS2dFE",
    "what do you mean":         "https://www.youtube.com/watch?v=DK_0jXPuIr0",
    "peaches":                  "https://www.youtube.com/watch?v=tQ0yjYMFYkk",
    "ghost":                    "https://www.youtube.com/watch?v=vnNDPBJCMGE",
    "stuck with u":             "https://www.youtube.com/watch?v=wLCm8FDhRcI",
    "intentions":               "https://www.youtube.com/watch?v=Z5fmK-BnUB4",
    "yummy":                    "https://www.youtube.com/watch?v=3DFmJFfvMKk",
    "anyone":                   "https://www.youtube.com/watch?v=P3cffdsEXXw",
    "as long as you love me":   "https://www.youtube.com/watch?v=_sSVNHNMKSE",
    "one time":                 "https://www.youtube.com/watch?v=_2UOsIKKmgQ",

    # ── Dua Lipa ─────────────────────────────────────────────────────────────
    "levitating":               "https://www.youtube.com/watch?v=TlTQmCBCCAw",
    "new rules":                "https://www.youtube.com/watch?v=k2qgadSvNyU",
    "dont start now":           "https://www.youtube.com/watch?v=oygrmJFKYZY",
    "physical":                 "https://www.youtube.com/watch?v=9HDEHj2yzew",
    "break my heart":           "https://www.youtube.com/watch?v=Nj2U6rhnucI",
    "one kiss":                 "https://www.youtube.com/watch?v=B3eAMGXFw1o",
    "cold heart":               "https://www.youtube.com/watch?v=naFMBFDGJJk",
    "we are good":              "https://www.youtube.com/watch?v=Kfh7G4dHjKo",
    "hotter than hell":         "https://www.youtube.com/watch?v=xVoRa5fx5lI",
    "be the one":               "https://www.youtube.com/watch?v=7SJ4J9ERk3A",
    "pretty please":            "https://www.youtube.com/watch?v=wJ7NMdmIZVc",
    "future nostalgia":         "https://www.youtube.com/watch?v=wcrzbFye11w",

    # ── Bollywood Blockbusters ────────────────────────────────────────────────
    "chaiyya chaiyya":          "https://www.youtube.com/watch?v=7RMOzCBMFdM",
    "dil chahta hai":           "https://www.youtube.com/watch?v=5e3mcMFqEXI",
    "kal ho na ho":             "https://www.youtube.com/watch?v=O6DEIMJ51QM",
    "tujhe dekha to":           "https://www.youtube.com/watch?v=fbSFoGanVPs",
    "kabhi khushi kabhi gham":  "https://www.youtube.com/watch?v=NaWKZgjEXaE",
    "vande mataram":            "https://www.youtube.com/watch?v=yivbyS9nSdQ",
    "jai ho":                   "https://www.youtube.com/watch?v=XYLVL8NNkpA",
    "bulleya":                  "https://www.youtube.com/watch?v=JlBBBPRGo0Q",
    "tere bina":                "https://www.youtube.com/watch?v=3HKCflDK-9k",
    "ghungroo":                 "https://www.youtube.com/watch?v=qFsFgOKWqCU",
    "teri ban jaungi":          "https://www.youtube.com/watch?v=rPNeQRLqv7E",
    "dilbar":                   "https://www.youtube.com/watch?v=irN7sCvKDaE",
    "lut gaye":                 "https://www.youtube.com/watch?v=_lsPEbF5WhM",
    "pasoori":                  "https://www.youtube.com/watch?v=TzH7yMdFCVM",
    "husn":                     "https://www.youtube.com/watch?v=LPcjFGjbOEk",
    "softly":                   "https://www.youtube.com/watch?v=HoCRhEhYjNg",
    "nain tare":                "https://www.youtube.com/watch?v=k0iOXE5OAAQ",
    "sajni":                    "https://www.youtube.com/watch?v=Hk6bSRRPR3c",
    "night drive":              "https://www.youtube.com/watch?v=KDpQcCMuMHI",

    # ── English / International ───────────────────────────────────────────────
    "shape of you":             "https://www.youtube.com/watch?v=JGwWNGJdvx8",
    "blinding lights":          "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
    "stay":                     "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    "perfect":                  "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
    "something just like this": "https://www.youtube.com/watch?v=FM7MFYoylVs",
    "bad guy":                  "https://www.youtube.com/watch?v=DyDfgMOUjCI",
    "dance monkey":             "https://www.youtube.com/watch?v=q0hyYWKXF0Q",
    "sunflower":                "https://www.youtube.com/watch?v=ApXoWvfEYVU",
    "rockstar":                 "https://www.youtube.com/watch?v=E4WlUXrJgy4",
    "believer":                 "https://www.youtube.com/watch?v=7wtfhZwyrcc",
    "thunder":                  "https://www.youtube.com/watch?v=fKopy74weus",
    "radioactive":              "https://www.youtube.com/watch?v=ktvTqknDobU",
    "demons":                   "https://www.youtube.com/watch?v=mWRsgZuwf_8",
    "counting stars":           "https://www.youtube.com/watch?v=hT_nvWreIhg",
    "let her go":               "https://www.youtube.com/watch?v=RBumgq5yVrA",
    "someone like you":         "https://www.youtube.com/watch?v=hLQl3WQQoQ0",
    "rolling in the deep":      "https://www.youtube.com/watch?v=rYEDA3JcQqw",
    "happy":                    "https://www.youtube.com/watch?v=y6Sxv-sUYtM",
    "uptown funk":              "https://www.youtube.com/watch?v=OPf0YbXqDm0",
    "take me to church":        "https://www.youtube.com/watch?v=PVjiKRfKpPI",
    "shallow":                  "https://www.youtube.com/watch?v=bo_efYhYU2A",
    "senorita":                 "https://www.youtube.com/watch?v=Pkh8UtuejGw",
    "memories":                 "https://www.youtube.com/watch?v=SlPhMPnQ58k",
    "drivers license":          "https://www.youtube.com/watch?v=ZmDBbnmKpqQ",
    "good 4 u":                 "https://www.youtube.com/watch?v=gNi_6U5Pm_o",

    # ── Lofi / Chill / Focus ──────────────────────────────────────────────────
    "lofi hip hop":             "https://www.youtube.com/watch?v=jfKfPfyJRdk",
    "chill lofi":               "https://www.youtube.com/watch?v=5qap5aO4i9A",
    "study music":              "https://www.youtube.com/watch?v=4xDzrJKXOOY",
    "deep focus":               "https://www.youtube.com/watch?v=b1zZAbhbgXA",
    "night lofi":               "https://www.youtube.com/watch?v=rUxyKA_-grg",

    # ── Iron Man / Marvel Cinematic ───────────────────────────────────────────
    "iron man theme":           "https://www.youtube.com/watch?v=FtU-O5dNfXE",
    "avengers theme":           "https://www.youtube.com/watch?v=7QUtEmBT_-w",
    "endgame theme":            "https://www.youtube.com/watch?v=xEdvFuJxnzQ",

}
